"""
SRE Decision Environment — Core Implementation.

This replaces the echo scaffold generated by `openenv init`.

Dec-POMDP design:
- Hidden root cause lives inside the environment, never exposed to the agent.
- Noisy sensor modules (logs, observer) generate partial observations.
- Orchestrator agent acts on observations only.
- Episode terminates when the agent calls a terminal action or max_steps reached.

Phase 1 — OpenEnv scaffold + hidden-state environment.
"""

import logging
import random
from typing import Optional
from uuid import uuid4

from openenv.core.env_server.interfaces import Environment
from openenv.core.env_server.types import State

import sys as _sys
from pathlib import Path as _Path

# Ensure parent dirs are on sys.path so imports work both as package and standalone.
_here = _Path(__file__).resolve().parent          # .../server/
_parent = _here.parent                             # .../sre_decision_env/
for _p in (_here, _parent):
    if str(_p) not in _sys.path:
        _sys.path.insert(0, str(_p))

try:
    from ..models import VALID_ACTIONS, SreDecisionAction, SreDecisionObservation
    from .sensors import ROOT_CAUSES, get_logs_signal, get_observer_signal
    from .rewards import compute_step_reward
except ImportError:
    from models import VALID_ACTIONS, SreDecisionAction, SreDecisionObservation  # type: ignore
    from sensors import ROOT_CAUSES, get_logs_signal, get_observer_signal        # type: ignore
    from rewards import compute_step_reward                                      # type: ignore

logger = logging.getLogger(__name__)

# Episode configuration
MAX_STEPS: int = 10
TERMINAL_ACTIONS = {"resolve_incident"}


class SreDecisionEnvironment(Environment):
    """
    SRE Incident-Response Environment (Phase 1).

    The hidden ``_root_cause`` is sampled once per episode in ``reset()``.
    The agent receives only noisy ``SreDecisionObservation`` objects and must
    choose from the structured ``SreDecisionAction`` action space.

    Lifecycle::

        env = SreDecisionEnvironment()
        obs = env.reset()           # new episode, new hidden root cause
        while True:
            action = agent.act(obs)
            result = env.step(action)
            obs = result.observation
            if result.done:
                break
    """

    SUPPORTS_CONCURRENT_SESSIONS: bool = True

    # -----------------------------------------------------------------
    # Initialisation
    # -----------------------------------------------------------------

    def __init__(self) -> None:
        """Initialise environment with an empty (pre-reset) state."""
        self._state = State(episode_id=str(uuid4()), step_count=0)
        self._root_cause: Optional[str] = None
        self._done: bool = False
        self._last_action: Optional[str] = None
        self._episode_rewards: list[float] = []
        self._history: list[str] = []

    # -----------------------------------------------------------------
    # Reset
    # -----------------------------------------------------------------

    def reset(self) -> SreDecisionObservation:
        """
        Start a new episode with a freshly sampled hidden root cause.

        The root cause is deliberately never included in the returned
        observation — the agent must infer it from sensor signals.

        Returns:
            Initial SreDecisionObservation (before any action is taken).
        """
        self._root_cause = random.choice(ROOT_CAUSES)
        self._state = State(episode_id=str(uuid4()), step_count=0)
        self._done = False
        self._last_action = None
        self._episode_rewards = []
        self._history = []

        logger.info(
            "Episode reset. root_cause=%s episode_id=%s",
            self._root_cause,
            self._state.episode_id,
        )

        logs = get_logs_signal(self._root_cause)
        observer = get_observer_signal(self._root_cause)

        return SreDecisionObservation(
            logs=logs,
            observer=observer,
            time_step=0,
            last_action=None,
            action_feedback="A new SRE incident has been detected. Begin your investigation.",
            incident_resolved=False,
            available_actions=VALID_ACTIONS,
        )

    # -----------------------------------------------------------------
    # Step
    # -----------------------------------------------------------------

    def step(self, action: SreDecisionAction) -> SreDecisionObservation:  # type: ignore[override]
        """
        Execute one decision step.

        Args:
            action: Structured action from the orchestrator agent.

        Returns:
            New SreDecisionObservation reflecting the updated world state.
        """
        if self._done:
            # Guard: episode already terminated
            return self._terminal_obs(
                "Episode is already over. Call reset() to start a new one."
            )

        if self._root_cause is None:
            # Guard: reset() was never called
            raise RuntimeError("reset() must be called before step().")

        self._state.step_count += 1
        action_name = action.action_name.strip().lower()
        is_valid = action_name in VALID_ACTIONS

        # --- Check episode termination before reward ---
        is_terminal_action = action_name in TERMINAL_ACTIONS
        timed_out = self._state.step_count >= MAX_STEPS
        
        if is_terminal_action or timed_out:
            self._done = True

        # --- Check diagnosis state ---
        diagnosed = any(a in ["inspect_logs", "inspect_metrics"] for a in self._history)

        # --- Compute reward for this step ---
        reward, step_breakdown = compute_step_reward(
            action_name=action_name,
            root_cause=self._root_cause,
            step=self._state.step_count,
            max_steps=MAX_STEPS,
            is_valid=is_valid,
            history=self._history,
            diagnosed=diagnosed,
            resolved=is_terminal_action
        )
        self._episode_rewards.append(reward)
        self._last_action = action_name
        self._history.append(action_name)

        # --- Determine feedback message ---
        feedback = self._build_feedback(action_name, is_valid)

        if self._done:
            logger.info(
                "Episode ended. root_cause=%s action=%s steps=%d total_reward=%.2f",
                self._root_cause,
                action_name,
                self._state.step_count,
                sum(self._episode_rewards),
            )

            
        full_breakdown = step_breakdown

        # --- Build next observation ---
        logs = get_logs_signal(self._root_cause)
        observer = get_observer_signal(self._root_cause)

        return SreDecisionObservation(
            logs=logs,
            observer=observer,
            time_step=self._state.step_count,
            last_action=action_name,
            action_feedback=feedback,
            incident_resolved=self._done,
            available_actions=VALID_ACTIONS,
            done=self._done,
            reward=reward,
            metadata={
                "root_cause_hidden": True,  # never expose real value
                "step": self._state.step_count,
                "episode_id": self._state.episode_id,
                "total_reward_so_far": round(sum(self._episode_rewards), 4),
                "reward_breakdown": full_breakdown,
            },
        )

    # -----------------------------------------------------------------
    # Helpers
    # -----------------------------------------------------------------

    def _build_feedback(self, action_name: str, is_valid: bool) -> str:
        """Generate human-readable feedback for the agent's last action."""
        if not is_valid:
            return (
                f"Unknown action '{action_name}'. "
                f"Valid actions: {', '.join(VALID_ACTIONS)}."
            )
        messages = {
            "inspect_logs": "Logs scanned. New signals are reflected in the observation.",
            "inspect_metrics": "Metrics collected. Observer signals have been refreshed.",
            "check_deploy_history": "Deploy history reviewed. No additional signals surfaced.",
            "declare_severity_low": "Incident severity declared as LOW.",
            "declare_severity_high": "Incident severity declared as HIGH.",
            "restart_service": "Service restart initiated. Awaiting stabilisation.",
            "rollback_service": "Rollback initiated. Reverting to last stable deployment.",
            "resolve_incident": "Incident marked as resolved. Episode complete.",
        }
        return messages.get(action_name, f"Action '{action_name}' executed.")

    def _terminal_obs(self, feedback: str) -> SreDecisionObservation:
        """Return a terminal placeholder observation."""
        return SreDecisionObservation(
            logs={},
            observer={},
            time_step=self._state.step_count,
            last_action=self._last_action,
            action_feedback=feedback,
            incident_resolved=True,
            available_actions=[],
            done=True,
            reward=0.0,
        )

    # -----------------------------------------------------------------
    # OpenEnv interface property
    # -----------------------------------------------------------------

    @property
    def state(self) -> State:
        """Return the current episode state (episode_id + step_count)."""
        return self._state
